package com.phoenix.tests.caqa.testproc.Cobrands.Component;
public class AutoComplete {
 static public String xml = "<testproc package=\"Cobrands.Component\" name=\"AutoComplete\">\n"
  +"<desc></desc>	<params>\n"
  +"<param name=\"Lang\" value=\"fr\"/>\n"
  +"</params>	<ss>\n"
  +"<s><l></l><c>SET Actions = Actions</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>SET FNB = FNB</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>IF {Lang}==fr</c><e></e><a>GOTO n0</a><t></t><n></n></s>\n"
  +"<s><l></l><c>SET Actions = Equities</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>SET FNB = ETFs</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l>n0</l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>ClearTypeKeys(\"//input[@id='quote-search-header']\",\"bbd\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyContent(\"//div[@class='qs-autoCompleteBox-wrap']//tr[@class='qs-autocomplete-column-title'][2]/td\")</c><e>Options</e><a></a><t></t><n>Check if Options exist</n></s>\n"
  +"<s><l></l><c>ClearTypeKeys(\"//input[@id='quote-search-header']\",\"BBD7AKC00600\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>SLEEP 1000</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyContent(\"//div[@class='qs-autoCompleteBox-wrap']/table/tbody\")</c><e>Montreal</e><a></a><t></t><n>Check there are Montreal(Canada)</n></s>\n"
  +"<s><l></l><c>VerifyContent(\"//div[@class='qs-autoCompleteBox-wrap']/table/tbody\")</c><e>CBOE</e><a></a><t></t><n> Check there are CBOE(US)</n></s>\n"
  +"<s><l></l><c>ClearTypeKeys(\"//input[@id='quote-search-header']\",\"bom\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>SLEEP 1000</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyContent(\"//div[@class='qs-autoCompleteBox-wrap']//tr[@class='qs-autocomplete-column-title'][1]/td\")</c><e>{Actions}</e><a></a><t></t><n>Check if Equities exist in table</n></s>\n"
  +"<s><l></l><c>VerifyContent(\"//div[@class='qs-autoCompleteBox-wrap']//tr[@class='qs-autocomplete-column-title'][2]/td\")</c><e>{FNB}</e><a></a><t></t><n>Check if ETFs exist in table</n></s>\n"
  +"<s><l></l><c>ClearTypeKeys(\"//input[@id='quote-search-header']\",\"goog\")</c><e></e><a></a><t></t><n>Enter an US stock</n></s>\n"
  +"<s><l></l><c>SLEEP 1000</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyContent(\"//td[@class='qs-autocomplete-col-clientticker']\")</c><e>GOOG(L?)-U</e><a></a><t></t><n>Check -U for US stock</n></s>\n"
  +"<s><l></l><c>ClearTypeKeys(\"//input[@id='quote-search-header']\",\"td\")</c><e></e><a></a><t></t><n>Enter a Canada stock</n></s>\n"
  +"<s><l></l><c>SLEEP 1000</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyElement(\"//td[@class='qs-autocomplete-col-clientticker']\")</c><e>TD-C</e><a></a><t></t><n>Check -C for Canada stock</n></s>\n"
  +"<s><l></l><c>SET i = 1</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l>Loop1</l><c>INC i</c><e></e><a></a><t></t><n>Start with index 2</n></s>\n"
  +"<s><l></l><c>IF {i}&gt;20</c><e></e><a>FAIL</a><t>CONT</t><n></n></s>\n"
  +"<s><l></l><c>VerifyContent(\"//td[@class='qs-autocomplete-col-clientticker'][{i}]\")</c><e>TD-U</e><a>CONT</a><t>[1000]GOTO Loop1</t><n>Check TD-U exist and -U is after -C</n></s>\n"
  +"<s><l></l><c>ClearTypeKeys(\"//input[@id='quote-search-header']\",\"RAY/\")</c><e></e><a></a><t></t><n>Try with \"/\"</n></s>\n"
  +"<s><l></l><c>SLEEP 3000</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyElement(\"(//div[@class='qs-autoCompleteBox-wrap'])[3]\")</c><e></e><a>FAIL</a><t>[1000]CONT</t><n>Should not include \"/\".</n></s>\n"
  +"<s><l></l><c>ClearTypeKeys(\"//input[@id='quote-search-header']\",\"RAY/B-C\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>Click(\"//button[@id='quote-search-button-header']\")</c><e></e><a></a><t></t><n>search RAY/B-C</n></s>\n"
  +"<s><l></l><c>SLEEP 1000</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyContent(\"//div[@class='quote-description s9-widget-header-title']\")</c><e>RAY.B-C</e><a></a><t></t><n>Ray/B-C Should appear as Ray.B-C</n></s>\n"
  +"<s><l></l><c>ClearTypeKeys(\"//input[@id='quote-search-header']\",\"KKKK-C\")</c><e></e><a></a><t></t><n>Try invalid symbol</n></s>\n"
  +"<s><l></l><c>Click(\"//button[@id='quote-search-button-header']\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyElement(\"//div[@id='quoteWidgetsErrorArea']\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"</ss>\n"
  +"	<owner>mengdi 2016.06.07</owner>	<modifier>mengdi 2016.06.10</modifier>\n"
  +"</testproc>";
}
