package com.phoenix.tests.caqa.testproc.Cobrands.Disnat;
public class Login {
 static public String xml = "<testproc package=\"Cobrands.Disnat\" name=\"Login\">\n"
  +"<desc></desc>	<params>\n"
  +"<param name=\"Lang\" value=\"fr\"/>\n"
  +"<param name=\"user\" value=\"MSTR1\"/>\n"
  +"<param name=\"pass\" value=\"12345b\"/>\n"
  +"</params>	<ss>\n"
  +"<s><l></l><c>SET _L =</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>IF {Lang}==fr</c><e></e><a>GOTO n0</a><t></t><n></n></s>\n"
  +"<s><l></l><c>SET _L = en</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l>n0</l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l>#</l><c>VerifyElement(\"//img[@src='/solution9-dc/images/logo-S9DC-fr@2x.png']\")</c><e></e><a>CONT</a><t>[3000]GOTO no_win1</t><n></n></s>\n"
  +"<s><l></l><c>VerifyElement(\"[3]\")</c><e></e><a>CONT</a><t>[1000]GOTO no_win3</t><n></n></s>\n"
  +"<s><l></l><c>CloseWindow(\"[3]\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l>no_win3</l><c>VerifyElement(\"[2]\")</c><e></e><a>CONT</a><t>[1000]GOTO no_win2</t><n></n></s>\n"
  +"<s><l></l><c>CloseWindow(\"[2]\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l>no_win2</l><c>VerifyElement(\"[1]\")</c><e></e><a>GOTO no_win1</a><t>[1000]GOTO no_win1</t><n></n></s>\n"
  +"<s><l></l><c>VerifyElement(\"//a[@id='btnQtr']\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyContent(\"//a[@id='btnLng']\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>IF {Lang}==fr AND {$1}==English</c><e></e><a>PASS</a><t>CONT</t><n></n></s>\n"
  +"<s><l></l><c>IF {Lang}==en AND {$1}==Fran\u00e7ais</c><e></e><a>PASS</a><t>CONT</t><n></n></s>\n"
  +"<s><l></l><c>Click(\"//a[@id='btnLng']\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyElement(\"//img[@src='/solution9-dc/images/logo-S9DC-fr@2x.png']\")</c><e></e><a>CONT</a><t>[3000]GOTO no_win1</t><n></n></s>\n"
  +"<s><l></l><c>RET PASS</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l>no_win1</l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>Open(\"https://www.disnat.com/{_L}\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>ClickIfExist(\"//button[@class='btn-white lock']\")</c><e></e><a></a><t>[1000]</t><n></n></s>\n"
  +"<s><l></l><c>SLEEP 4000</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>Input(\"//input[@id='username']\",\"{user}\")</c><e></e><a></a><t></t><n>Eneter username MSTR1</n></s>\n"
  +"<s><l></l><c>ClickIfExist(\"//input[@class='btn login-btn']\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>VerifyElement(\"//div[@id='form-group-question']\")</c><e></e><a>CONT</a><t>[3000]GOTO n2</t><n></n></s>\n"
  +"<s><l></l><c>Input(\"//input[@id='answer']\",\"111\")</c><e></e><a></a><t></t><n>answer as 111</n></s>\n"
  +"<s><l></l><c>Click(\"//button[@class='btn btn-primary btn-submit pull-right']\")</c><e></e><a></a><t></t><n>click enter</n></s>\n"
  +"<s><l>n2</l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c>Input(\"//input[@id='j_password']\",\"{pass}\")</c><e></e><a></a><t></t><n>password as 12345b</n></s>\n"
  +"<s><l></l><c>Click(\"//button[@class='btn btn-primary btn-submit pull-right']\")</c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"<s><l></l><c></c><e></e><a></a><t></t><n></n></s>\n"
  +"</ss>\n"
  +"	<owner>mengdi 2016.06.07</owner>	<modifier>mengdi 2016.06.16</modifier>\n"
  +"</testproc>";
}
