package com.morningstar.phoenix.tests.caqa.testproc.MStarCA;

public class Home {
	static public String xml = "<testproc package=\"MStarCA\" name=\"Home\">\n"
			+ "<desc>v4 created on 2016-05-12 - support french\n" + "v3 created on 2016-03-10\n"
			+ "v2 created on 2015-07-15\n" + "</desc>	<params>\n" + "<param name=\"Lang\" value=\"en\"/>\n"
			+ "</params>	<ss>\n" + "<s><l></l><c>CALL Login()</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Video = Video</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Funds = Funds</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET PersonalFinance = Personal Finance</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Encounter = Encounter</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET ETFs = ETFs</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FundNews= Fund News</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET ETFNews = ETF News</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Markets =Markets</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET StockAnalystUpdates =Stock Analyst Updates</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET CommodityFutures = Commodity Futures</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Tools = Tools</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET ProductDownloads = Product Downloads</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET MarketIndexes = Market Indexes</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET MorningstarCDN = @MorningstarCDN</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET AnalystReports = Analyst Reports</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET ManagerMonitor = Manager Monitor</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FiveStarFunds = Five Star Funds</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET AnalystReview = Analyst Review</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FundQuickrank =Fund Quickrank</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FundLookup =Fund Lookup</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FundFinder = Fund Finder</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET ETFFinder = ETF Finder</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET SimilarFunds =Similar Funds</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FundCompare =Fund Compare</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Stewardship = Stewardship</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c></c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>GOTO en1</c><e></e><a>GOTO en1</a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Video = Vid\u00e9o</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET PersonalFinance = Finances personnelles</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Encounter = Rencontre</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET ETFs = Perspectives investisseurs</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Funds = Perspectives des gestionnaires</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FundNews = Actualit\u00e9 Fonds</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET ETFNews = Actualit\u00e9 FNB</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Markets =March\u00e9s</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET StockAnalystUpdates = Mises \u00e0 jour des analystes d?actions (contenu en anglais)</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET CommodityFutures = Contrat \u00e0 terme sur marchandises</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Tools = Outils</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET ProductDownloads = T\u00e9l\u00e9chargement de produits</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET MarketIndexes = Indices des march\u00e9s</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET MorningstarCDN = @MstarCDNfr</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET AnalystReports =Rapports des analystes</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET ManagerMonitor = Suivi des gestionnaires</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FiveStarFunds = Fonds 5 \u00e9toiles</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET AnalystReview = Avis d\u2019analyste</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FundQuickrank = R\u00e9pertoire</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FundLookup = Recherche de fonds</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FundFinder =D\u00e9celeur de fonds</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET ETFFinder = D\u00e9celeur de FNB</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET SimilarFunds = Fonds semblables</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET FundCompare = Comparer des fonds</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SET Stewardship = G\u00e9rance</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l>en1</l><c></c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//A[@id='nav_home']\")</c><e></e><a></a><t></t><n>(TC1) Click on [home] Tab</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//DIV[@id='HP_VideoReport']//DIV[@textContents='{Video}']\")</c><e></e><a></a><t></t><n>(TC2) Verify Section Title [Video]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//div[@class='section_b1']//DIV[@textContents='{Funds}']\")</c><e></e><a></a><t></t><n>(TC3) Verify Section Title [Funds]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//div[@class='section_b1']//DIV[@textContents='{Encounter}']\")</c><e></e><a></a><t></t><n>(TC4) Verify Section Title [Encounter]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//div[@class='section_b1']//DIV[@textContents='{PersonalFinance}']\")</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//div[@class='section_b1']//DIV[@textContents='{ETFs}']\")</c><e></e><a></a><t></t><n>(TC6) Verify Section Title [ETFs]</n></s>\n"
			+ "<s><l>#</l><c>VerifyElement(\"//div[@class='section_b1']//DIV[@textContents='Stocks']\")</c><e></e><a></a><t></t><n>(TC7) Verify Section Title [Stocks]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//div[@class='section_a1']/DIV[@textContents='{FundNews}']\")</c><e></e><a></a><t></t><n>(TC9) Verify Section Title [Fund News]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//div[@class='section_a1']/DIV[@textContents='{ETFNews}']\")</c><e></e><a></a><t></t><n>(TC10) Verify Section Title [ETF News]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//div[@class='section_a1']/DIV[@textContents='{Markets}']\")</c><e></e><a></a><t></t><n>(TC11) Verify Section Title [Markets]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//DIV[@textContents='{StockAnalystUpdates}']\")</c><e></e><a></a><t></t><n>(TC12) Verify Section Title [Stock Analyst Updates]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//DIV[@textContents='{CommodityFutures}']\")</c><e></e><a></a><t></t><n>(TC13) Verify Section Title [Commodity Futures]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//div[@id='mshp_commodityfuture']\")</c><e></e><a></a><t></t><n>(TC14) Verify Section Frame [Commodity Futures]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//DIV[@textContents='{Tools}']\")</c><e></e><a></a><t></t><n>(TC15) Verify Section Title [Tools]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//DIV[@textContents='{ProductDownloads}']\")</c><e></e><a></a><t></t><n>(TC16) Verify Section Title [Product Downloads]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//DIV[@textContents='{MarketIndexes}']\")</c><e></e><a></a><t></t><n>(TC17) Verify Section Title [Market Index]</n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//div[@id='mshp_mktindex']\")</c><e></e><a></a><t></t><n>(TC19) Verify Market index Ifram </n></s>\n"
			+ "<s><l></l><c>VerifyElement(\"//iframe//h1[starts-with(normalize-space(.),'Tweets')]\")</c><e></e><a></a><t></t><n>(TC26) Verify DomClick Twitter feed widge content[Tweets]</n></s>\n"
			+ "<s><l></l><c>Click(\"//a[@text='\u200e{MorningstarCDN}']\")</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>SLEEP 1000</c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>CloseWindow(\"//BrowserApplication[2]\")</c><e></e><a></a><t></t><n>(TC28) Close Tweets window</n></s>\n"
			+ "<s><l>#</l><c></c><e></e><a></a><t></t><n></n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[1]\")</c><e>{AnalystReports}</e><a></a><t></t><n>Verify that analyst reports are there</n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[2]\")</c><e>{ManagerMonitor}</e><a></a><t></t><n>(TC32) Verify Content[Manager Monitor']</n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[3]\")</c><e>{FiveStarFunds}</e><a></a><t></t><n>(TC33) Verify Content[Five Star Funds]</n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[4]\")</c><e>{AnalystReview}</e><a></a><t></t><n>Verify Analyst Review</n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[5]\")</c><e>{FundQuickrank}</e><a></a><t></t><n>Verify Quickran</n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[6]\")</c><e>{FundLookup}</e><a></a><t></t><n>Verify Lookup</n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[7]\")</c><e>{FundFinder}</e><a></a><t></t><n>Verify Fund Finder</n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[8]\")</c><e>{ETFFinder}</e><a></a><t></t><n>Verify ETF Finder</n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[9]\")</c><e>{SimilarFunds}</e><a></a><t></t><n>Verify Similar Funds</n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[10]\")</c><e>{FundCompare}</e><a></a><t></t><n>Verify Fund Compare</n></s>\n"
			+ "<s><l></l><c>VerifyContent(\"//div[@id='mshp_staticlinks']/div[1]/a[11]\")</c><e>{Stewardship}</e><a></a><t></t><n>Verify Stewardship</n></s>\n"
			+ "</ss>\n" + "	<owner>mengdi 2016.05.12</owner>	<modifier>mengdi 2016.07.12</modifier>\n"
			+ "</testproc>";
}
